name: Upload to Test PyPI

on:
  push:
    #branches:
    #  - pypi-test # Only run workflow on my test branch
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build distribution package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    permissions: # Reqyured for OpenID Connect
      id-token: write

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Check tag and version matches
        run: |
          GIT_TAG=$(git describe --tags --abbrev=0)
          make check-version RELEASE_TAG=$GIT_TAG

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install twine and build
        run: |
          python -m pip install twine build

      #- name: Install dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install .[dev]

      #- name: Build package
      #  run: python -m build

      #- name: Publish package to PyPI
      #  run: |
      #    python -m twine upload --repository testpypi dist/* --verbose
